name: 'Setup LaTeX action'
author: 'Mr. Kin'
description: 'Setup LaTeX environment for doc class'
runs:
  using: "composite"
  steps:
    - name: Setup TeX Live
      uses: TeX-Live/setup-texlive-action@v3
      with:
        package-file: ${{ github.action_path }}/tex_live_packages

    - name: Download latex fonts version file
      run: |
        curl -s -L -O https://github.com/Mister-Kin/OpenDocs/releases/download/latexfonts/latex_fonts_version
      shell: bash

    - name: Cache LaTeXFonts
      id: cache-latexfonts
      uses: actions/cache@v4
      with:
        path: ./LaTeXFonts
        key: cache-latexfonts-${{ hashFiles('./latex_fonts_version') }}

    - name: Delete latex fonts version file
      run: |
        rm latex_fonts_version
      shell: bash

    - if: ${{ steps.cache-latexfonts.outputs.cache-hit != 'true' }}
      name: Download LaTeX Fonts
      run: |
        curl -s -L -O https://github.com/Mister-Kin/OpenDocs/releases/download/latexfonts/LaTeXFonts.7z
        7z x LaTeXFonts.7z
      shell: bash

    - name: Install and refresh LaTeXFonts
      run: |
        cp -a ./LaTeXFonts /usr/share/fonts/
        fc-cache -f -v -r
      shell: bash
